### ISSUE TITLE
search radius is hard coded

### ISSUE THREAD

**Issue by dnarayanan** [dnarayanan/caesar#15]
in `simulation_attributes.py` we have:

```	self.search_radius   = ds.quan(1000.0, sru).to(obj.units['length'])```

this is hard coded and we should make this a run time argument possibility

**Comment by christopherlovell** [comment]
It would also be useful to specify _multiple_ search radii

**Comment by dnarayanan** [comment]
fixed by @romeeld with this commit:

db29e3c02866ffd2d9de93999c7516ab3acb43b6
