### ISSUE TITLE
NotImplementedError for simulations with no SMBHs

### ISSUE THREAD

**Issue by rennehan** [dnarayanan/caesar#48]
Hi, I've been trying to use caesar on simulations with no supermassive black holes and found a little circular bug that occurs in the property manager.

Specifically, on line 146 a NotImplementedError is raised in the get_ptype_name() function:

```python
    def get_ptype_name(self, requested_ptype):
        """Gets the correct ptype name for this dataset.
        Parameters
        ----------
        requested_ptype : str
            Typically 'gas','dm','star','bh'
        Returns
        -------
        str
            The proper ptype name for a given dataset.
        """        
        if not self.has_ptype(requested_ptype):
            raise NotImplementedError('Could not find %s ptype!' % requested_ptype)
        return self.ptype_aliases[requested_ptype.lower()]
```

Here is a link: https://github.com/dnarayanan/caesar/blob/cd92546f1dd9e88d49c2a7bbfe393dbf185cfc54/caesar/property_manager.py#L146

However, get_ptype_name() is used in has_property() but the exception is not caught! So if the property does not exist the execution halts at the exception rather than continuing without that particle type.  That occurs here:

```python
    def has_property(self, requested_ptype, requested_prop):
        """Returns True/False if requested property/field is present.
        Parameters
        ----------
        requested_ptype : str
            Typically 'gas','dm','star','bh'
        requested_prop : str
            Requested property/field.
        Returns
        -------
        boolean
            True if property/field is present, False otherwise.
        """
        prop  = self.get_property_name(requested_ptype, requested_prop)
        ptype = self.get_ptype_name(requested_ptype)

        if ptype in self.ds.particle_fields_by_type:
            fields = self.ds.particle_fields_by_type[ptype]
            if prop in fields:
                return True
    
        fields = self.ds.derived_field_list
        for f in fields:
            if f[0] == ptype and f[1] == prop:
                return True

        return False
```

I put a **try...except...** statement in has_property() that returns False on the exception, as a temporary fix. That seems to work fine but maybe there is a more elegant solution.

**Comment by dnarayanan** [comment]
thanks for identifying this Doug!   there probably *is* a more fancy solution than try/except....but I'm not pythonic enough to know it :).  would you want to PR with the try/except solution?
