### ISSUE TITLE
Zoom-in simulation halo offsets

### ISSUE THREAD

**Issue by rennehan** [dnarayanan/caesar#60]
Hello! 

I am running a zoom-in simulation of a cluster and using caesar for the halo analysis. For some reason, the halo positions in the output caesar file do not correspond to any real positions of matter in the simulation or to the associated galaxies.

Here is an image that should clarify what I mean. As you can see, the position of the most massive halo does not even correspond to its associated most massive galaxy, nor is the halo position within the zoom region. I noticed this when trying to make projections of all of the halos, and they were all outside of the zoom region. 

![caesar_issue](https://user-images.githubusercontent.com/32492248/141003746-ed7a90ea-bfc6-4125-aeba-82a4276e5adf.png)

I am not sure what is going on, but hopefully someone has some insight! Thanks :)

**Comment by dnarayanan** [comment]
thanks for the helpful screen shot!   I have to admit I don't know exactly what's going on.  @rthompsonj and I chatted on slack about this and think it must be some sort of units issue.

To confirm - the entire zoom in region is constrained within [713249,759212] in kpccm?    As in, caesar is finding `obj.halos[0].pos` as a position that is outside the range of any dark matter particle in the HDF5 file?

another way of asking this is - if we were to visualize the snapshot (say, in a projection plot or something), the position of halo 0 wouldn't even be on the image?

**Comment by romeeld** [comment]
I wrote this on Desika's slack: I’ve seen this kind of thing occasionally.  halo.pos is the CoM of the halo.  We almost never use that because the 3DFOF can do weird things sometimes (see Thompson et al 2015 :).  Instead we use halo.minpotpos, which is the minimum potential particle, usually within the most massive galaxy.
But tbh I don't know how the pos can get that screwed up... maybe something about periodic boundaries being done wrong?

**Comment by rennehan** [comment]
> To confirm - the entire zoom in region is constrained within [713249,759212] in kpccm? As in, caesar is finding `obj.halos[0].pos` as a position that is outside the range of any dark matter particle in the HDF5 file?
> 
> another way of asking this is - if we were to visualize the snapshot (say, in a projection plot or something), the position of halo 0 wouldn't even be on the image?

Yes, indeed! For further information, the DM coords are correct inside of the dmlist. Also, the min/max of the DM particles are correct.

![real_dm_coords](https://user-images.githubusercontent.com/32492248/141008640-3005773e-a9b4-40cb-8aca-1c5af0bb89a0.png)

with:

np.amin(halo_dm_coords) gives 717449.75
np.amax(halo_dm_coords) gives 750414.6

Also, all of the coordinates in the simulation data look like they are within the zoom region:

![all_coords](https://user-images.githubusercontent.com/32492248/141009226-7ea07371-3b1d-4ed7-9598-fa7dbad6d2f4.png)

The minpotpos is indeed within the zoom region:

unyt_array([731471.125, 745241.625, 742240.375], dtype=float32, units=‘kpccm’)

**Comment by weiguangcui** [comment]
I think the only solution is to save the group[0] data in the nogil_CoM_quants to see what is going wrong.

**Comment by rennehan** [comment]
The center values are known to be off. The minpotpos is much more accurate to the true center and should be used.
