### ISSUE TITLE
Misplaced print statement causing install to fail

### ISSUE THREAD

**Issue by FredJenningsAstro** [dnarayanan/caesar#76]
When I clone and install caesar I get 

```  
File "/home/fjennings/.conda/envs/analysis_xrays/lib/python3.11/site-packages/caesar-0.2b0-py3.11-linux-x86_64.egg/caesar/group.py", line 853
    elif part_type == 'dust': suffix='dlist'
    ^^^^
SyntaxError: invalid syntax
```

due to the print statement on line 852 splitting the elifs

**Comment by dnarayanan** [comment]
thanks - i just fixed!  sorry about that.  i spent 5 minutes trying to get it to raise a telling message if the code barfs there but couldn't figure it out so just put in that janky print statement.

**Comment by FredJenningsAstro** [comment]
Haha, no worries at all, thanks for fixing! :)

**Comment by dnarayanan** [comment]
please do let me know if you encounter any bugs in your most recent pull - the updates i put in over the last few days are all for arepo where dust is stuffed into PartType3 - i did a couple of quick tests on an old simba snapshot but haven't tested extensively so would appreciate a report if anything has broken!
