### ISSUE TITLE
sys not imported

### ISSUE THREAD

**Issue by rennehan** [dnarayanan/caesar#8]
https://github.com/dnarayanan/caesar/blob/442949d7cbaa564ac297cebe423f39a84edb88d1/caesar/fof6d.py#L91

The sys package has not been imported in this code block. It seems like there are a lot of cases where this happens, perhaps just a single global import would work fine?

**Comment by saethlin** [comment]
This and a few other such bugs should now be fixed. Can you confirm that things are working for you now?

**Comment by rennehan** [comment]
Yes indeed, thanks.
