### ISSUE TITLE
Installation Error unknown file type '.pyx'

### ISSUE THREAD

**Issue by her7man** [dnarayanan/caesar#85]
'caesar.group_funcs' extension
error: unknown file type '.pyx' (from 'caesar/group_funcs/group_funcs.pyx')

**Comment by weiguangcui** [comment]
Hi, may you confirm that `cython` has been installed correctly?

**Comment by her7man** [comment]
> 
Hello, Yes, I installed version 0.29.24

**Comment by weiguangcui** [comment]
May you show the complete compiling output? It seems to me that your python can not find the cython you have installed. Make sure that the installed cython path is included in your python environment.

**Comment by her7man** [comment]
Thanks for you help, here is the outoout
$ sudo python3 setup.py install

/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
writing caesar.egg-info/PKG-INFO
writing dependency_links to caesar.egg-info/dependency_links.txt
writing entry points to caesar.egg-info/entry_points.txt
writing requirements to caesar.egg-info/requires.txt
writing top-level names to caesar.egg-info/top_level.txt
reading manifest file 'caesar.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'caesar.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'caesar.group_funcs' extension
error: unknown file type '.pyx' (from 'caesar/group_funcs/group_funcs.pyx')

**Comment by weiguangcui** [comment]
I still think your python3 can not find the cython package. can you import cython with your python3?

**Comment by her7man** [comment]
Yes i can
when I installed pygadgetreader there are no problem, and I installed caesar previous version (last year) it worked

**Comment by her7man** [comment]
Yes i can
when I installed pygadgetreader there are no problem, and I installed caesar previous version (last year) it worked

**Comment by her7man** [comment]
Yes i can
when I installed pygadgetreader there are no problem, and I installed caesar previous version (last year) it worked

**Comment by weiguangcui** [comment]
pygadgetread doesn't need cython, only caesar requires that. 
May you try this to see if it works:
`python3 setup.py install --user`

**Comment by her7man** [comment]
It's always the same error.

**Comment by her7man** [comment]
> pygadgetread doesn't need cython, only caesar requires that. May you try this to see if it works: `python3 setup.py install --user`
It's always the same error,

**Comment by her7man** [comment]
So! I reinstall the Cython 
/sudo pip install cython
And I try to run the setup.py after.
It was solved!
Thank you very much for the help.

**Comment by weiguangcui** [comment]
OK, glad that has been solved.
