### ISSUE TITLE
Bug with cKDTree positions

### ISSUE THREAD

**Issue by EwanBJones98** [dnarayanan/caesar#95]
I have recently ran into an odd bug when calling the `scipy.spatial.cKDTree` function within `calculate_local_densities` in caesar/utils.py. I have managed to fix this by swapping the code currently present for a functionally identical (as far as I can tell) numpy function. Just wanted to share this issue here as I am still unsure what has caused this to happen.

This is the relevant code snippet:
```
 pos  = np.array([i.pos for i in group_list])
 mass = np.array([i.masses['total'] for i in group_list])
 box  = obj.simulation.boxsize
 box  = np.array([box,box,box])
 for i in range(3):
        pos[pos[:,i]>box[i], i] -= box[i]
        pos[pos[:,i]<0, i] += box[i]
TREE = cKDTree(pos, boxsize=obj.simulation.boxsize)
```

The error I was getting was from `cKDTree`, in which it said that there were positions outside of the bounds of the box, and the code would crash. The loop seen in the code snippet just before the call to `cKDTree` is moving particles to be within the boxsize using the periodic boundary conditions. However, upon printing the maximum positions of particles in each coordinate axis after this loop, I noticed that the array slicing was not catching some particles in the `i=2` coordinate axis which exceeded the boxsize. Due to this, the `cKDTree` function was throwing a `ValueError` and crashing the code.

I replaced this loop with the following:
```
np.mod(pos,box,out=pos)
``` 
which handles all three coordinate directions at once. Functionally this achieves the same goal as the previous implementation, however it does not miss these particles which are exceeding the boxsize. My Caesar code has ran fine on the offending snapshot with this change implemented.

I am unsure what is wrong with the original implementation such that these coordinates are missed with the array slicing method but not by using the `numpy.mod` function.

**Comment by EwanBJones98** [comment]
I have now opened a pull request containing my fix for this issue.

**Comment by dnarayanan** [comment]
i think i lost track of this - was this solved in the PR (i.e. can we close?)

**Comment by EwanBJones98** [comment]
> i think i lost track of this - was this solved in the PR (i.e. can we close?)

Yeah this was solved in the PR, should be good to close.
